### ISSUE TITLE
Video links doesn't work

### ISSUE THREAD

**Issue by MrTheBarbarian** [malvinas2/screensaver.video#6]
Hi!Video links doesn't work. Can I have get it some how?
Thanks!

**Comment by malvinas2** [comment]
You can find some screensaver videos on YouTube or at the links given below. 
[https://github.com/RobinFrcd/AerialShots](https://github.com/RobinFrcd/AerialShots)
[https://aerial-screensavers.netlify.app/](https://aerial-screensavers.netlify.app/)
[https://docs.google.com/spreadsheets/d/1bboTohF06r-fafrImTExAPqM9m6h2m2lgJyAkQuYVJI/edit#gid=1684411812](https://docs.google.com/spreadsheets/d/1bboTohF06r-fafrImTExAPqM9m6h2m2lgJyAkQuYVJI/edit#gid=1684411812)
